version: "3.9"

services:
    nginx:
        image: testchovui/nginx
        container_name: nginx
        ports:
        - "80:80"
        # volumes:
        #   - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
        - api

    pgadmin:
        image: testchovui/pgadmin
        container_name: pgadmin
        ports:
        - "5050:80"

    postgres:
        image: testchovui/postgres
        container_name: postgres
        # ports:
        #     - "5432:5432"
        # volumes:
        #     - postgres_data:/var/lib/postgresql/data
 
    # postgres:
    #     image: postgres/lastest
    #     container_name: postgres
    #     restart: always
    #     environment:
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: 12345678
    #         POSTGRES_DB: mystore
    #     volumes:
    #         - postgres_data:/var/lib/postgresql/data

    api:
        image: testchovui/api  # Thay bằng tên image đã tải
        container_name: api
        ports:
        - "8081:8080"
        # environment:
        #   DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
        depends_on:
        - postgres

    frontend:
        image: testchovui/frontend  # Thay bằng tên image đã tải
        container_name: frontend
        ports:
        - "5173:5173"

volumes:
  postgres_data:
