version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: store
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres
    # ports:
    #   - "5432:5432"
  webapi:
    container_name: webapi
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - postgres
      - nginx_network
    ports:
      - "8081:8080"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.com
      PGADMIN_DEFAULT_PASSWORD: aaa
      # PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:80"
    networks: 
      - postgres
      - nginx_network

  nginx:
    image: nginx
    container_name: nginx_container
    depends_on:
      - pgadmin
      - webapi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./README.md:/static/documentation/README.md
      # - ./img/:/static/documentation/img/
      - ./static:/static
    ports:
      - "80:80"
    networks:
      - nginx_network

volumes:
  postgres-data:
networks:
  postgres:
    driver: bridge
  nginx_network:
    driver: bridge